import dotenv from 'dotenv'
dotenv.config()

const TWITTER_API_KEY = process.env.TWITTER_API_KEY
const TWITTER_API_SECRET = process.env.TWITTER_API_SECRET
const TWITTER_ACCESS_TOKEN = process.env.TWITTER_ACCESS_TOKEN
const TWITTER_BEARER_TOKEN = process.env.TWITTER_BEARER_TOKEN
const TWITTER_TOKEN_SECRET = process.env.TWITTER_TOKEN_SECRET
const TWITTER_ELON_USER_ID = 44196397

const CRYPTO_COM_URL = process.env.CRYPTO_COM_URL
const CRYPTO_COM_TOKEN = process.env.CRYPTO_COM_TOKEN

export default {
    TWITTER_API_KEY,
    TWITTER_API_SECRET,
    TWITTER_ACCESS_TOKEN,
    TWITTER_BEARER_TOKEN,
    TWITTER_TOKEN_SECRET,
    TWITTER_ELON_USER_ID
}